2024-03-15 20:06:44,822 INFO    StreamThr :9696 [internal.py:wandb_internal():86] W&B internal server running at pid: 9696, started at: 2024-03-15 20:06:44.821377
2024-03-15 20:06:44,823 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status
2024-03-15 20:06:44,824 INFO    WriterThread:9696 [datastore.py:open_for_write():87] open: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\run-t9wotqaj.wandb
2024-03-15 20:06:44,825 DEBUG   SenderThread:9696 [sender.py:send():382] send: header
2024-03-15 20:06:44,825 DEBUG   SenderThread:9696 [sender.py:send():382] send: run
2024-03-15 20:06:45,613 INFO    SenderThread:9696 [dir_watcher.py:__init__():211] watching files in: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files
2024-03-15 20:06:45,613 INFO    SenderThread:9696 [sender.py:_start_run_threads():1136] run started: t9wotqaj with start time 1710529603.859799
2024-03-15 20:06:45,626 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: check_version
2024-03-15 20:06:45,626 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: check_version
2024-03-15 20:06:46,146 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: run_start
2024-03-15 20:06:46,157 DEBUG   HandlerThread:9696 [system_info.py:__init__():27] System info init
2024-03-15 20:06:46,157 DEBUG   HandlerThread:9696 [system_info.py:__init__():42] System info init done
2024-03-15 20:06:46,157 INFO    HandlerThread:9696 [system_monitor.py:start():194] Starting system monitor
2024-03-15 20:06:46,158 INFO    SystemMonitor:9696 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-15 20:06:46,158 INFO    HandlerThread:9696 [system_monitor.py:probe():214] Collecting system info
2024-03-15 20:06:46,160 INFO    SystemMonitor:9696 [interfaces.py:start():190] Started cpu monitoring
2024-03-15 20:06:46,161 INFO    SystemMonitor:9696 [interfaces.py:start():190] Started disk monitoring
2024-03-15 20:06:46,163 DEBUG   HandlerThread:9696 [system_info.py:probe():151] Probing system
2024-03-15 20:06:46,163 INFO    SystemMonitor:9696 [interfaces.py:start():190] Started gpu monitoring
2024-03-15 20:06:46,167 INFO    SystemMonitor:9696 [interfaces.py:start():190] Started memory monitoring
2024-03-15 20:06:46,179 INFO    SystemMonitor:9696 [interfaces.py:start():190] Started network monitoring
2024-03-15 20:06:46,179 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:46,179 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:46,181 DEBUG   HandlerThread:9696 [system_info.py:_probe_git():136] Probing git
2024-03-15 20:06:46,261 DEBUG   HandlerThread:9696 [system_info.py:_probe_git():144] Probing git done
2024-03-15 20:06:46,261 DEBUG   HandlerThread:9696 [system_info.py:probe():199] Probing system done
2024-03-15 20:06:46,261 DEBUG   HandlerThread:9696 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.11.8', 'heartbeatAt': '2024-03-15T19:06:46.163304', 'startedAt': '2024-03-15T19:06:34.204266', 'docker': None, 'cuda': None, 'args': (), 'state': 'running', 'program': '<python with no main file>', 'codePathLocal': None, 'git': {'remote': 'https://github.com/BaiardiLorenzo/DLA.git', 'commit': 'd5a0551a5a26530be6356611f7c19e605f233a60'}, 'email': 'lorebaia@gmail.com', 'root': 'C:/Users/loreb/Documents/IntellijProjects/PycharmProjects/DLA', 'host': 'BlackPC', 'username': 'loreb', 'executable': 'c:\\src\\anaconda3\\envs\\DLA\\python.exe', 'cpu_count': 6, 'cpu_count_logical': 6, 'cpu_freq': {'current': 3600.0, 'min': 0.0, 'max': 3600.0}, 'cpu_freq_per_core': [{'current': 3600.0, 'min': 0.0, 'max': 3600.0}], 'disk': {'/': {'total': 232.08644485473633, 'used': 141.99224853515625}}, 'gpu': 'NVIDIA GeForce GTX 1050 Ti', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce GTX 1050 Ti', 'memory_total': 4294967296}], 'memory': {'total': 15.958698272705078}}
2024-03-15 20:06:46,262 INFO    HandlerThread:9696 [system_monitor.py:probe():224] Finished collecting system info
2024-03-15 20:06:46,262 INFO    HandlerThread:9696 [system_monitor.py:probe():227] Publishing system info
2024-03-15 20:06:46,262 DEBUG   HandlerThread:9696 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-03-15 20:06:46,622 INFO    Thread-171:9696 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\conda-environment.yaml
2024-03-15 20:06:48,201 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:48,201 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:49,125 DEBUG   HandlerThread:9696 [system_info.py:_save_conda():220] Saving conda packages done
2024-03-15 20:06:49,125 INFO    HandlerThread:9696 [system_monitor.py:probe():229] Finished publishing system info
2024-03-15 20:06:49,126 DEBUG   SenderThread:9696 [sender.py:send():382] send: files
2024-03-15 20:06:49,126 INFO    SenderThread:9696 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-03-15 20:06:49,139 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: python_packages
2024-03-15 20:06:49,139 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: python_packages
2024-03-15 20:06:49,139 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:06:49,140 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:06:49,141 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:06:49,653 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\conda-environment.yaml
2024-03-15 20:06:49,654 INFO    Thread-171:9696 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\requirements.txt
2024-03-15 20:06:49,654 INFO    Thread-171:9696 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\wandb-metadata.json
2024-03-15 20:06:49,744 DEBUG   SenderThread:9696 [sender.py:send():382] send: telemetry
2024-03-15 20:06:50,121 INFO    wandb-upload_0:9696 [upload_job.py:push():131] Uploaded file C:\Users\loreb\AppData\Local\Temp\tmpb_mq8u09wandb\j9pyteaw-wandb-metadata.json
2024-03-15 20:06:50,217 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:50,217 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:50,659 INFO    Thread-171:9696 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:06:50,752 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:06:52,245 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:52,245 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:52,677 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:06:54,265 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:54,265 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:55,797 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:06:56,294 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:56,295 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:58,318 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:06:58,318 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:00,373 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:00,373 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:00,896 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:02,415 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:02,415 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:02,729 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:04,153 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:07:04,157 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:07:04,157 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:07:04,461 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:04,461 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:04,740 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:05,962 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:06,485 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:06,485 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:06,768 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:08,532 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:08,532 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:08,781 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:10,555 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:10,555 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:10,597 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: partial_history
2024-03-15 20:07:10,597 DEBUG   SenderThread:9696 [sender.py:send():382] send: history
2024-03-15 20:07:10,598 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: summary_record
2024-03-15 20:07:10,598 INFO    SenderThread:9696 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-15 20:07:10,798 INFO    Thread-171:9696 [dir_watcher.py:_on_file_created():271] file/dir created: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\wandb-summary.json
2024-03-15 20:07:11,616 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:11,833 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:12,577 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:12,577 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:14,603 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:14,603 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:16,643 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:16,658 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:07:16,661 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:16,661 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:16,891 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\config.yaml
2024-03-15 20:07:18,677 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:18,678 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:19,158 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:07:19,174 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:07:19,174 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:07:20,683 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:20,683 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:22,213 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:22,711 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:22,711 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:23,995 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:24,743 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:24,743 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:26,015 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:26,766 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:26,766 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:27,223 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:28,033 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:28,796 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:28,796 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:30,047 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:30,969 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:30,969 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:32,083 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\output.log
2024-03-15 20:07:32,276 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:32,980 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:32,981 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:34,172 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:07:34,186 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:07:34,186 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:07:34,987 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:34,987 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:37,010 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:37,011 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:37,384 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:39,026 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:39,026 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:41,049 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:41,050 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:42,445 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:43,066 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:43,066 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:45,090 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:45,090 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:46,189 DEBUG   SystemMonitor:9696 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-15 20:07:46,190 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:07:47,136 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:07:47,138 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:47,138 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:48,200 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:49,146 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:49,146 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:49,186 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:07:49,201 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:07:49,201 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:07:51,150 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:51,150 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:53,161 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:53,161 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:53,487 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:55,179 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:55,180 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:57,194 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:57,194 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:58,551 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:07:59,211 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:07:59,211 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:01,227 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:01,227 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:03,255 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:03,256 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:03,613 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:04,201 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:08:04,216 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:08:04,216 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:08:05,277 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:05,277 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:07,297 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:07,297 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:09,315 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:09,315 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:09,598 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:11,334 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:11,334 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:13,357 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:13,357 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:14,636 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:15,378 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:15,378 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:16,194 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:08:16,344 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:08:17,431 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:08:17,434 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:17,434 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:19,205 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:08:19,221 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:08:19,221 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:08:19,449 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:19,449 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:20,422 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:21,463 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:21,463 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:23,488 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:23,488 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:25,500 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:25,504 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:25,504 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:27,527 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:27,528 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:29,548 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:29,548 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:30,554 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:31,572 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:31,573 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:33,602 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:33,602 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:34,215 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:08:34,241 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:08:34,242 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:08:35,618 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:35,618 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:36,508 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:37,637 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:37,637 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:39,653 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:39,653 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:41,539 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:41,674 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:41,674 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:43,708 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:43,708 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:45,729 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:45,729 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:46,210 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:08:46,361 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:08:47,213 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:47,776 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:08:47,782 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:47,782 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:49,226 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:08:49,239 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:08:49,240 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:08:49,787 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:49,787 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:51,792 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:51,792 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:52,491 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:53,821 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:53,821 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:55,839 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:55,839 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:57,537 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:08:57,856 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:57,856 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:59,872 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:08:59,872 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:01,882 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:01,882 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:02,588 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:03,905 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:03,905 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:04,222 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:09:04,242 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:09:04,243 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:09:05,920 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:05,920 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:07,937 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:07,937 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:08,545 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:09,955 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:09,955 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:11,972 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:11,972 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:13,593 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:13,989 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:13,990 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:16,006 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:16,006 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:16,223 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:09:16,373 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:09:18,047 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:09:18,054 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:18,054 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:19,224 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:09:19,225 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:19,255 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:09:19,255 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:09:20,056 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:20,056 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:22,072 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:22,072 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:24,088 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:24,088 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:24,474 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:26,106 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:26,106 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:28,123 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:28,123 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:29,510 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:30,136 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:30,136 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:32,151 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:32,151 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:34,172 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:34,172 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:34,227 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:09:34,259 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:09:34,259 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:09:35,481 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:36,191 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:36,192 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:38,218 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:38,218 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:40,235 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:40,236 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:40,527 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:42,274 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:42,274 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:44,311 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:44,311 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:45,560 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:46,237 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:09:46,324 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:46,324 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:46,390 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:09:48,380 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:09:48,390 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:48,390 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:49,240 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:09:49,271 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:09:49,272 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:09:50,405 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:50,405 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:51,478 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:52,427 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:52,427 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:54,462 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:54,462 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:56,517 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:56,517 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:56,537 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:09:58,541 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:09:58,541 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:00,581 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:00,581 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:01,577 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:02,598 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:02,598 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:04,244 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:10:04,274 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:10:04,274 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:10:04,610 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:04,610 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:06,630 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:06,630 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:07,479 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:08,655 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:08,655 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:10,673 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:10,673 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:12,526 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:12,688 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:12,688 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:14,707 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:14,707 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:16,243 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:10:16,397 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:10:16,724 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:16,724 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:18,250 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:18,777 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:10:18,780 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:18,780 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:19,260 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:10:19,295 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:10:19,295 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:10:20,794 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:20,794 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:22,798 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:22,798 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:23,544 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:24,817 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:24,817 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:26,843 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:26,843 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:28,589 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:28,863 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:28,863 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:30,880 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:30,880 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:32,902 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:32,902 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:33,637 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:34,264 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:10:34,308 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:10:34,308 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:10:34,920 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:34,921 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:36,939 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:36,939 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:38,955 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:38,955 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:39,575 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:40,967 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:40,967 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:42,976 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:42,976 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:44,606 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:44,980 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:44,981 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:46,247 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:10:46,405 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:10:47,004 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:47,004 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:49,038 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:10:49,054 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:49,055 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:49,276 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:10:49,322 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:10:49,322 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:10:50,545 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:51,078 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:51,078 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:53,094 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:53,094 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:55,108 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:55,108 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:55,577 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:10:57,132 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:57,132 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:59,166 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:10:59,166 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:00,615 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:01,187 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:01,188 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:03,204 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:03,204 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:04,290 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:11:04,338 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:11:04,338 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:11:05,230 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:05,230 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:06,578 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:07,255 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:07,255 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:09,270 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:09,272 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:11,282 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:11,282 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:11,605 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:13,437 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:13,438 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:15,456 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:15,457 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:16,260 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:11:16,413 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:11:17,262 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:17,481 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:17,481 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:19,291 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:11:19,353 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:11:19,353 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:11:19,534 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:11:19,540 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:19,540 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:21,547 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:21,547 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:22,660 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:23,551 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:23,551 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:25,571 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:25,571 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:27,591 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:27,591 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:27,702 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:29,611 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:29,611 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:31,639 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:31,639 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:32,739 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:33,660 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:33,660 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:34,301 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-15 20:11:34,375 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: stop_status
2024-03-15 20:11:34,375 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: stop_status
2024-03-15 20:11:35,679 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:35,679 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:37,695 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:37,695 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:38,660 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:39,715 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:39,715 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:41,731 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:41,732 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:43,716 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:43,760 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:43,761 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:45,793 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:45,793 ERROR   gpu       :9696 [interfaces.py:monitor():144] Failed to sample metric: Not Supported
2024-03-15 20:11:46,120 DEBUG   SenderThread:9696 [sender.py:send():382] send: telemetry
2024-03-15 20:11:46,122 DEBUG   SenderThread:9696 [sender.py:send():382] send: exit
2024-03-15 20:11:46,122 INFO    SenderThread:9696 [sender.py:send_exit():589] handling exit code: 0
2024-03-15 20:11:46,122 INFO    SenderThread:9696 [sender.py:send_exit():591] handling runtime: 299
2024-03-15 20:11:46,122 INFO    SenderThread:9696 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-15 20:11:46,122 INFO    SenderThread:9696 [sender.py:send_exit():597] send defer
2024-03-15 20:11:46,123 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,123 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 0
2024-03-15 20:11:46,123 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,123 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 0
2024-03-15 20:11:46,123 INFO    SenderThread:9696 [sender.py:transition_state():617] send defer: 1
2024-03-15 20:11:46,123 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,123 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 1
2024-03-15 20:11:46,123 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,123 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 1
2024-03-15 20:11:46,123 INFO    SenderThread:9696 [sender.py:transition_state():617] send defer: 2
2024-03-15 20:11:46,124 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,124 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 2
2024-03-15 20:11:46,124 INFO    HandlerThread:9696 [system_monitor.py:finish():203] Stopping system monitor
2024-03-15 20:11:46,124 DEBUG   SystemMonitor:9696 [system_monitor.py:_start():179] Finished system metrics aggregation loop
2024-03-15 20:11:46,124 DEBUG   SystemMonitor:9696 [system_monitor.py:_start():183] Publishing last batch of metrics
2024-03-15 20:11:46,125 INFO    HandlerThread:9696 [interfaces.py:finish():202] Joined cpu monitor
2024-03-15 20:11:46,129 INFO    HandlerThread:9696 [interfaces.py:finish():202] Joined disk monitor
2024-03-15 20:11:46,154 ERROR   gpu       :9696 [interfaces.py:aggregate():161] Failed to serialize metric: division by zero
2024-03-15 20:11:46,154 INFO    HandlerThread:9696 [interfaces.py:finish():202] Joined gpu monitor
2024-03-15 20:11:46,154 INFO    HandlerThread:9696 [interfaces.py:finish():202] Joined memory monitor
2024-03-15 20:11:46,154 INFO    HandlerThread:9696 [interfaces.py:finish():202] Joined network monitor
2024-03-15 20:11:46,154 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,155 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 2
2024-03-15 20:11:46,155 INFO    SenderThread:9696 [sender.py:transition_state():617] send defer: 3
2024-03-15 20:11:46,155 DEBUG   SenderThread:9696 [sender.py:send():382] send: stats
2024-03-15 20:11:46,155 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,155 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 3
2024-03-15 20:11:46,155 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,155 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 3
2024-03-15 20:11:46,155 INFO    SenderThread:9696 [sender.py:transition_state():617] send defer: 4
2024-03-15 20:11:46,156 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,156 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 4
2024-03-15 20:11:46,156 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,156 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 4
2024-03-15 20:11:46,156 INFO    SenderThread:9696 [sender.py:transition_state():617] send defer: 5
2024-03-15 20:11:46,156 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,156 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 5
2024-03-15 20:11:46,157 DEBUG   SenderThread:9696 [sender.py:send():382] send: summary
2024-03-15 20:11:46,158 INFO    SenderThread:9696 [sender.py:_save_file():1403] saving file wandb-summary.json with policy end
2024-03-15 20:11:46,158 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,158 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 5
2024-03-15 20:11:46,158 INFO    SenderThread:9696 [sender.py:transition_state():617] send defer: 6
2024-03-15 20:11:46,158 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: defer
2024-03-15 20:11:46,159 INFO    HandlerThread:9696 [handler.py:handle_request_defer():172] handle defer: 6
2024-03-15 20:11:46,159 DEBUG   SenderThread:9696 [sender.py:send_request():409] send_request: defer
2024-03-15 20:11:46,159 INFO    SenderThread:9696 [sender.py:send_request_defer():613] handle sender defer: 6
2024-03-15 20:11:46,162 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: status_report
2024-03-15 20:11:46,319 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:11:46,319 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:11:46,534 INFO    Thread-171:9696 [dir_watcher.py:_on_file_modified():288] file/dir modified: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\files\wandb-summary.json
2024-03-15 20:11:47,132 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: poll_exit
2024-03-15 20:11:47,737 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:11:47,737 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:11:49,945 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:11:49,946 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:11:49,946 INFO    SenderThread:9696 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2024-03-15 20:11:52,179 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:11:54,336 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:11:54,336 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:11:57,217 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:02,234 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:02,678 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:12:02,678 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:12:07,275 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:12,300 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:16,323 ERROR   FileStreamThread:9696 [file_stream.py:_handle_response():504] dropped chunk 404 Client Error: Not Found for url: https://api.wandb.ai/files/lorebaia/DLA%20Assigment%201/t9wotqaj/file_stream
NoneType: None
2024-03-15 20:12:17,335 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:20,565 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:12:20,565 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:12:22,369 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:27,401 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:32,421 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:37,477 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:42,537 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:47,598 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:52,631 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:12:53,368 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:12:53,368 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:12:57,670 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:13:02,705 DEBUG   HandlerThread:9696 [handler.py:handle_request():146] handle_request: keepalive
2024-03-15 20:14:03,801 ERROR   SenderThread:9696 [internal_api.py:execute():373] 409 response executing GraphQL.
2024-03-15 20:14:03,801 ERROR   SenderThread:9696 [internal_api.py:execute():374] {"errors":[{"message":"run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2024-03-15 20:14:04,123 INFO    WriterThread:9696 [datastore.py:close():296] close: c:\Users\loreb\Documents\IntellijProjects\PycharmProjects\DLA\wandb\run-20240315_200634-t9wotqaj\run-t9wotqaj.wandb
2024-03-15 20:14:04,123 INFO    HandlerThread:9696 [handler.py:finish():869] shutting down handler
2024-03-15 20:14:04,161 ERROR   StreamThr :9696 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\apis\normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 2216, in upsert_run
    response = self.gql(
               ^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 341, in gql
    ret = self._retry_gql(
          ^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal_api.py", line 369, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\vendor\gql-0.2.0\wandb_gql\client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\lib\gql_request.py", line 59, in execute
    request.raise_for_status()
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\requests\models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal_util.py", line 49, in run
    self._run()
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal_util.py", line 100, in _run
    self._process(record)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\internal.py", line 328, in _process
    self._sm.send(record)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\sender.py", line 389, in send
    send_handler(record)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\sender.py", line 411, in send_request
    send_handler(record)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\sender.py", line 639, in send_request_defer
    self.debounce(final=True)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\sender.py", line 540, in debounce
    self._maybe_update_config(always=final)
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\sender.py", line 517, in _maybe_update_config
    self._debounce_config()
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\sdk\internal\sender.py", line 546, in _debounce_config
    self._api.upsert_run(
  File "c:\src\anaconda3\envs\DLA\Lib\site-packages\wandb\apis\normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run lorebaia/DLA Assigment 1/t9wotqaj was previously created and deleted; try a new run name (Error 409: Conflict)
